export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN'
export const GET_CURRENT_USER_SUCCES = 'GET_CURRENT_USER_SUCCES'
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR'

export const UPDATE_VAULT_BEGIN = 'UPDATE_VAULT_BEGIN'
export const UPDATE_VAULT_SUCCESS = 'UPDATE_VAULT_SUCCESS'
export const UPDATE_VAULT_ERROR = 'UPDATE_VAULT_ERROR'

export const DELETE_VAULT_ITEM_BEGIN = 'DELETE_VAULT_ITEM_BEGIN'
export const DELETE_VAULT_ITEM_SUCCESS = 'DELETE_VAULT_ITEM_SUCCESS'
export const DELETE_VAULT_ITEM_ERROR = 'DELETE_VAULT_ITEM_ERROR'

export const LOGOUT = 'LOGOUT'

// TESTING CONSTANT
export const TEST = 'TEST'
